export const COMMON_VEGETABLES = ['高麗菜', '菠菜', '南瓜', '番茄', '豆腐', '金針菇'];

const standardStaples = [
  { id: 'purple-rice', name: '紫米飯', extraPrice: 0 },
  { id: 'buckwheat-noodles', name: '蕎麥麵', extraPrice: 0 },
  { id: 'wufeng-red-quinoa-rice', name: '霧峰紅黎飯', extraPrice: 15, note: '在地限定' },
];

export const MENU_CATEGORIES = [
  {
    id: 'beauty',
    name: '養顏美容',
    shortDescription: '日常美容保養與均衡飲食需求',
    color: 'pink',
    icon: 'sparkles',
    proteins: [
      { id: 'chicken-thigh', name: '雞腿肉', price: 298 },
      { id: 'tilapia', name: '鯛魚片', price: 298 },
      { id: 'lean-beef', name: '低脂牛', price: 369 },
      { id: 'pork-jowl', name: '松阪豬', price: 399 },
    ],
    baseSoups: [
      { id: 'tomato', name: '番茄', extraPrice: 0 },
      { id: 'pumpkin', name: '南瓜', extraPrice: 0 },
      { id: 'milk-broth', name: '牛奶白湯', extraPrice: 0 },
      { id: 'beef-bone-broth', name: '牛骨白湯', extraPrice: 0 },
    ],
    upgradeLabel: '升級湯底',
    upgradeSoups: [
      { id: 'pumpkin-milk', name: '南瓜牛奶', extraPrice: 65 },
      { id: 'tomato-milk', name: '蕃茄牛奶', extraPrice: 65 },
    ],
    specialVegetableLabel: '養顏專屬',
    specialVegetables: ['山藥', '紫薯', '蓮藕', '冬瓜', '海帶'],
    staples: standardStaples,
    recommendation: { proteinId: 'chicken-thigh', soupId: 'tomato', stapleId: 'purple-rice' },
  },
  {
    id: 'body-fat',
    name: '控制體脂',
    shortDescription: '清爽搭配與日常飲食管理',
    color: 'green',
    icon: 'leaf',
    proteins: [
      { id: 'chicken-thigh', name: '雞腿肉', price: 298 },
      { id: 'tilapia', name: '鯛魚片', price: 298 },
      { id: 'lean-beef', name: '低脂牛', price: 369 },
      { id: 'pork-jowl', name: '松阪豬', price: 399 },
    ],
    baseSoups: [
      { id: 'miso', name: '味噌', extraPrice: 0 },
      { id: 'kimchi', name: '泡菜', extraPrice: 0 },
      { id: 'bonito-kelp', name: '柴魚昆布', extraPrice: 0 },
    ],
    upgradeLabel: '代謝升級',
    upgradeSoups: [{ id: 'peeled-chili', name: '剝皮辣椒', extraPrice: 65 }],
    specialVegetableLabel: '減脂專屬',
    specialVegetables: ['白菜', '玉米筍', '茼蒿', '冬瓜', '花椰菜'],
    staples: standardStaples,
    recommendation: { proteinId: 'tilapia', soupId: 'bonito-kelp', stapleId: 'purple-rice' },
  },
  {
    id: 'vitality',
    name: '養氣補氣',
    shortDescription: '日常元氣與體力補給',
    color: 'yellow',
    icon: 'energy',
    proteins: [
      { id: 'chicken-thigh', name: '雞腿肉', price: 298 },
      { id: 'lean-beef', name: '低脂牛', price: 369 },
      { id: 'pork-jowl', name: '松阪豬', price: 399 },
    ],
    baseSoups: [
      { id: 'pumpkin', name: '南瓜', extraPrice: 0 },
      { id: 'chicken-broth', name: '雞湯', extraPrice: 0 },
      { id: 'herbal-soup-base', name: '藥膳湯底', extraPrice: 0 },
    ],
    upgradeLabel: '深層調理',
    upgradeSoups: [
      { id: 'ginger-sesame-oil', name: '薑母麻油', extraPrice: 65, seasonal: true, note: '冬季限定' },
      { id: 'ginseng-goji', name: '人參枸杞', extraPrice: 75 },
    ],
    specialVegetableLabel: '補氣專屬',
    specialVegetables: ['木耳', '山藥', '胡蘿蔔', '香菇'],
    staples: standardStaples,
    recommendation: { proteinId: 'chicken-thigh', soupId: 'chicken-broth', stapleId: 'purple-rice' },
  },
  {
    id: 'gut-health',
    name: '腸道健康',
    shortDescription: '高纖蔬菜與均衡日常選擇',
    color: 'blue',
    icon: 'activity',
    proteins: [
      { id: 'chicken-thigh', name: '雞腿肉', price: 298 },
      { id: 'pork-shoulder', name: '梅花豬', price: 298 },
      { id: 'lean-beef', name: '低脂牛', price: 369 },
      { id: 'pork-jowl', name: '松阪豬', price: 399 },
    ],
    baseSoups: [
      { id: 'miso', name: '味噌', extraPrice: 0 },
      { id: 'kimchi', name: '泡菜', extraPrice: 0 },
      { id: 'pumpkin', name: '南瓜', extraPrice: 0 },
      { id: 'bonito-kelp', name: '柴魚昆布', extraPrice: 0 },
    ],
    upgradeLabel: '健康升級',
    upgradeSoups: [
      { id: 'pumpkin-milk', name: '南瓜牛奶', extraPrice: 65 },
      { id: 'pickled-cabbage-pork', name: '酸菜白肉', extraPrice: 65 },
    ],
    specialVegetableLabel: '順腸專屬',
    specialVegetables: ['花椰菜', '牛蒡', '木耳', '玉米筍', '青江菜'],
    staples: standardStaples,
    recommendation: { proteinId: 'pork-shoulder', soupId: 'miso', stapleId: 'purple-rice' },
  },
  {
    id: 'immunity',
    name: '增強免疫',
    shortDescription: '日常防護與營養補給',
    color: 'indigo',
    icon: 'shield',
    proteins: [
      { id: 'chicken-thigh', name: '雞腿肉', price: 298 },
      { id: 'tilapia', name: '鯛魚片', price: 298 },
      { id: 'marbled-beef', name: '雪花牛', price: 369 },
      { id: 'lean-beef', name: '低脂牛', price: 369 },
    ],
    baseSoups: [
      { id: 'herbal', name: '藥膳', extraPrice: 0 },
      { id: 'garlic', name: '蒜香', extraPrice: 0 },
      { id: 'miso', name: '味噌', extraPrice: 0 },
      { id: 'kimchi', name: '泡菜', extraPrice: 0 },
    ],
    upgradeLabel: '免疫升級',
    upgradeSoups: [
      { id: 'ginseng-goji', name: '人參枸杞', extraPrice: 75, seasonal: true, note: '冬季限定' },
    ],
    specialVegetableLabel: '防護專屬',
    specialVegetables: ['花椰菜', '青江菜', '胡蘿蔔', '木耳', '玉米筍'],
    staples: standardStaples,
    recommendation: { proteinId: 'chicken-thigh', soupId: 'garlic', stapleId: 'purple-rice' },
  },
  {
    id: 'children',
    name: '兒童首選',
    shortDescription: '家庭共享・營養均衡・簡單好選',
    color: 'purple',
    icon: 'person',
    proteins: [
      { id: 'chicken-thigh', name: '雞腿肉', price: 298 },
      { id: 'pork-shoulder', name: '梅花豬', price: 298 },
      { id: 'marbled-beef', name: '雪花牛', price: 369 },
      { id: 'pork-jowl', name: '松阪豬', price: 399 },
    ],
    baseSoups: [
      { id: 'tomato', name: '番茄', extraPrice: 0 },
      { id: 'pumpkin', name: '南瓜', extraPrice: 0 },
      { id: 'miso', name: '味噌', extraPrice: 0 },
      { id: 'herbal', name: '藥膳', extraPrice: 0 },
      { id: 'chicken-broth', name: '雞湯', extraPrice: 0 },
      { id: 'bonito-kelp', name: '柴魚昆布', extraPrice: 0 },
    ],
    upgradeLabel: '',
    upgradeSoups: [],
    specialVegetableLabel: '成長專屬',
    specialVegetables: ['玉米筍', '黃豆芽', '胡蘿蔔', '花椰菜', '青江菜'],
    staples: [
      { id: 'udon', name: '烏龍麵', extraPrice: 0, note: '兒童限定' },
      { id: 'white-rice', name: '白飯', extraPrice: 0, note: '兒童限定' },
    ],
    recommendation: { proteinId: 'chicken-thigh', soupId: 'pumpkin', stapleId: 'udon' },
  },
  {
    id: 'vegetarian',
    name: '素食飲食',
    shortDescription: '純植物飲食・高纖維選擇',
    color: 'mint',
    icon: 'carrot',
    price: null,
    proteins: [],
    baseSoups: [
      { id: 'pumpkin', name: '南瓜', extraPrice: 0 },
      { id: 'tomato', name: '番茄', extraPrice: 0 },
      { id: 'herbal', name: '藥膳', extraPrice: 0 },
    ],
    upgradeLabel: '深層調理',
    upgradeSoups: [
      { id: 'pumpkin-milk', name: '南瓜牛奶', extraPrice: 65, note: '原始菜單品項，成分待確認' },
      { id: 'ginger-sesame-oil', name: '薑母麻油', extraPrice: 65, seasonal: true, note: '冬季限定' },
      { id: 'ginseng-goji', name: '人參枸杞', extraPrice: 75, note: '五辛（原始標註，歸屬待確認）' },
    ],
    specialVegetableLabel: '植感專屬',
    specialVegetables: ['天貝', '花椰菜', '白菜', '玉米筍', '木耳', '山藥'],
    staples: standardStaples,
    recommendation: { proteinId: null, soupId: 'pumpkin', stapleId: 'purple-rice' },
  },
];

export const getCategory = (categoryId) =>
  MENU_CATEGORIES.find((category) => category.id === categoryId);

export const getAllSoups = (category) => [
  ...category.baseSoups,
  ...(category.upgradeSoups || []),
];
